# CH32V003 / CH32X03x single-wire (SWIO) debugger.
# Speaks the ardulink serial protocol over USB-CDC, so minichlink drives it
# unmodified:  minichlink -C ardulink -c /dev/ttyACM0

TARGET := swio
SRC    := swio.c

include ../common/common.mk
